version: '3'
services:
       nica-ventas:
               image: galeanom26/nicaventa:nivel2
               build:
                       context: ./nica-ventas
                       dockerfile: Dockerfile
               ports:
                       - "8000:5000"
               volumes:
                       - ./nica-ventas/app:/app
               command: flask run --host=0.0.0.0
               environment:
                       - FLASK_DEBUG=1
                       - DATABASE_PASSWORD=nicaventaspass
                       - DATABASE_NAME=nicaventasdb
                       - DATABASE_USER=nicaventasuser
                       - DATABASE_HOST=nicaventas-db
                       - REDIS_LOCATION=redis
                       - REDIS_PORT=6379
               command: flask run --host=0.0.0.0
       nicaventas-db:
              image: mysql:5
              environment:
                      - MYSQL_ROOT_PASSWORD=123qwe
                      - MYSQL_DATABASE=nicaventasdb
                      - MYSQL_USER=nicaventasuser
                      - MYSQL_PASSWORD=nicaventaspass
              expose:
                     - 3306
              volumes:
                      - ./nica-ventas/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      
